# Generated by Django 4.2.9 on 2024-04-12 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('date', models.DateField()),
                ('product_name', models.CharField(max_length=100)),
                ('product_serial_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('opening_balance', models.IntegerField(blank=True)),
                ('closing_balance', models.IntegerField(blank=True)),
                ('sales', models.IntegerField(blank=True)),
                ('product_buying_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('product_selling_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('sales_tax', models.FloatField(max_length=20)),
                ('sale_discount', models.FloatField(blank=True)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Splice_display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('splice_photo', models.ImageField(upload_to='images/')),
                ('splice_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateField()),
                ('ordering_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_ordered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nav.product')),
            ],
        ),
        migrations.CreateModel(
            name='checkout_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField(max_length=250)),
                ('Card_number', models.CharField(max_length=15)),
                ('Card_name', models.CharField(max_length=200)),
                ('expiration_on_card', models.CharField(max_length=15)),
                ('Security_Code', models.PositiveIntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nav.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
