# Generated by Django 4.2.9 on 2024-02-20 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='nav.users_addresses'),
        ),
    ]
