# Generated by Django 4.2.9 on 2024-03-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Splice_display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('splice_photo', models.ImageField(upload_to='images/')),
                ('splice_description', models.CharField(max_length=200)),
            ],
        ),
    ]
