# Generated by Django 4.2.9 on 2024-02-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0002_alter_users_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='delivery_address',
        ),
        migrations.AlterField(
            model_name='users',
            name='user_address',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Users_Addresses',
        ),
    ]
