# Generated by Django 4.2.9 on 2024-03-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0002_splice_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toppicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_description', models.CharField(max_length=50)),
                ('pick_photo', models.ImageField(upload_to='images/')),
                ('pick_price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
