# Generated by Django 4.2.9 on 2024-02-22 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0003_remove_orders_delivery_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=100)),
                ('user_last_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_address', models.CharField(max_length=150)),
                ('favorite_items', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='nav.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nav.user'),
        ),
    ]
