# Generated by Django 4.2.9 on 2024-04-03 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0004_alter_product_product_buying_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='toppick_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nav.toppicks')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nav.user')),
            ],
        ),
    ]
