# Generated by Django 4.2.9 on 2024-04-03 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0005_toppick_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('menu_pick', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='nav.product')),
                ('toppick_product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='nav.toppicks')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nav.user')),
            ],
        ),
        migrations.DeleteModel(
            name='toppick_cart',
        ),
    ]
