# Generated by Django 4.2.9 on 2024-04-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0006_cartitems_delete_toppick_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='toppick_product',
            new_name='toppick_product_id',
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
