# Generated by Django 4.2.9 on 2024-04-03 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0008_alter_cartitems_user_id_alter_order_ordering_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='menu_pick',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nav.product'),
        ),
    ]
