# Generated by Django 4.2.9 on 2024-04-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0010_alter_cartitems_toppick_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='is_toppick',
            field=models.BooleanField(default=False),
        ),
    ]
