# Generated by Django 4.2.9 on 2024-04-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0013_cartitems_menu_cartitems_toppick_delete_cartitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems_toppick',
            old_name='user_id',
            new_name='cart_owner',
        ),
        migrations.RenameField(
            model_name='cartitems_toppick',
            old_name='toppick_product_id',
            new_name='toppick_cart_product',
        ),
    ]
