# Generated by Django 4.2.9 on 2024-04-09 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nav', '0014_rename_user_id_cartitems_toppick_cart_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField(max_length=250)),
                ('Card_number', models.CharField(max_length=15)),
                ('Card_name', models.CharField(max_length=200)),
                ('expiration_on_card', models.DateField()),
                ('Security_Code', models.PositiveIntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
