# Generated by Django 4.2.9 on 2024-04-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0015_checkout_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout_information',
            name='expiration_on_card',
            field=models.CharField(max_length=15),
        ),
    ]
